### ISSUE TITLE
[Improvement]: adding middleware to Ampli documentation

### ISSUE THREAD

**Issue by bogdan-karlenko** [Amplitude-Developer-Docs/amplitude-dev-center#133]
### Contact Details

bogdan.karlenko@gmail.com

### What can we improve?

Looks like `ampli.client.addEventMiddleware()` was changed to `ampli.addEventMiddleware()`
Docs need to be updated

### Which page needs an update?

https://www.docs.developers.amplitude.com/data/ampli/middleware/

**Comment by justin-fiedler** [comment]
Hi @bogdan-karlenko thanks for reaching out.

`ampli.client.addEventMiddleware()` is correct for all platforms except for Browser where it is `ampli.addMiddleware()` due to some technical reasons. We will work to update the docs to call out this inconsistency.
