### ISSUE TITLE
[Improvement]: Browser SDK missing EU Data residency section

### ISSUE THREAD

**Issue by salvatore-nastasi** [Amplitude-Developer-Docs/amplitude-dev-center#178]
### Contact Details

salvatore@amplitude.com

### What can we improve?

EU Data Residency section missing - need to call out explicitly how to init() on the EU servers with the setServerZone parameter for all our EU based customers. Please cross check other SDK docs that would require the same section.

### Which page needs an update?

https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/#initializing-sdk

**Comment by salvatore-nastasi** [comment]
related issue here: https://amplitude.atlassian.net/browse/AMP-57532

**Comment by salvatore-nastasi** [comment]
Note as I don't want to create a separate issue for this: The JS legacy sample code for EU server also has a typo:
https://www.docs.developers.amplitude.com/data/sdks/javascript/#eu-data-residency - the comma after true has to be removed to have a valid script...Thanks!

**Comment by caseyamp** [comment]
Fixed in #182
