### ISSUE TITLE
[Bug]: Postman collection not found

### ISSUE THREAD

**Issue by likith-lt** [Amplitude-Developer-Docs/amplitude-dev-center#179]
### Contact Details

likithk@lambdatest.com

### For API examples when I tried to fork the postman collection, I am getting the following message in postman -
```
Collection doesn't exist
This collection seems to have been deleted or is no longer public
```
<img width="554" alt="Screenshot 2022-07-27 at 2 51 40 PM" src="https://user-images.githubusercontent.com/97941433/181211747-c9ac90f9-2d38-49ab-86c9-a52edebe778b.png">

**Source** - 
<img width="840" alt="Screenshot 2022-07-27 at 2 52 07 PM" src="https://user-images.githubusercontent.com/97941433/181211847-4b4fb3f0-2eb1-4ad7-b222-9be34cba4f11.png">

**Comment by caseyamp** [comment]
Thanks for taking the time to report the problem @likith-lt -- the fix should be live within the next 5 minutes.
