### ISSUE TITLE
[Improvement]: Update group limit or clarify wording

### ISSUE THREAD

**Issue by ed-bassett** [Amplitude-Developer-Docs/amplitude-dev-center#184]
### Contact Details

ed@devsketchpad.com

### What can we improve?

Reading the docs for the **Group Identify API**, available with the **Accounts** add-on, it states that "You can track up to 5 unique group types and 10 total groups". I can understand the limit for group types, but it's inconceivable that there would be a limit of 10 total groups. The examples given in other areas of the documentation for the **Accounts** add-on ("a company of customers, a team of users, or a playlist with listeners"). For all these examples, you would expect any business (even the earliest stage startup) to have more than 10.

Could you please update the documentation with the actual limit (if there is one), or update them to better articulate what is meant by "total groups" if it means something different (perhaps the limit is per request, when `identification` is an array of JSON objects, or the limit applies to each individual user). I suspect it's the latter, as on https://www.docs.developers.amplitude.com/analytics/apis/identify-api/#required-parameters, the same limit is referenced regarding the `groups` parameter when identifying an individual user.

To clarify, the way I understand the current phrasing and meaning of "10 total groups" in the context of the **Group Identify API** is as follows:
If we were using the **Accounts** add-on to to track at a company level, we might have a `company` for each user (in reality we'd use ids, but using a names makes this easier to explain) to which each user belongs, e.g.
```
user: Alice, company: Amplitude
user: Bob, company: Amplitude
user: Sarah, company: Google
user: Fred, company: Netflix
```

We would like to track at the company level, so that whether an event is performed by Alice or Bob, it's still attributed to Amplitude, and we can look up events performed by Amplitude in any part of the UI that supports it.

To identify our groups we'd send:
```
[
  {"group_type":"company" ,"group_value":"Amplitude", "group_properties":{...}},
  {"group_type":"company" ,"group_value":"Google", "group_properties":{...}}},
  {"group_type":"company" ,"group_value":"Netflix", "group_properties":{...}}},
]
```
This would be "3 total groups", meaning we'd only be able to send another 7 before exhausting our limit of "10 total groups".

**Additional improvements**

Assuming the limit is per user, it would be great if you could provide more detail on what happens if this limit is exceeded. For example, if the following call is made:
```
amplitude.getInstance().logEventWithGroups('initialize_game', eventProperties, {'sport': 'Soccer'});
```
and (because this user is particularly sporty) we subsequently log 10 further events with `sport` set to `Ultimate Frisbee`, `Solo Synchronised Swimming`, `Parkour`, `Chess Boxing`, `Zorbing`, `Quidditch`, `Unicycle Polo`, `Curling`, `Tug-of-War`, and finally `Cheese Rolling`, what happens when the 11th event with `{'sport': 'Cheese Rolling'}`?

Does the event fail because the user is already in 10 sports? Do we stop being able to analyse that user's events where the event was logged with the least-recently-used group (Soccer)? Or is this actually fine, and the limit simply means we couldn't call `logEventWithGroups` with 11 groups for the user for one event?

### Which page needs an update?

https://www.docs.developers.amplitude.com/analytics/apis/group-identify-api/

**Comment by caseyamp** [comment]
Hi @ed-bassett -- I'm looking into this. Thanks!
