### ISSUE TITLE
Add instructions for finding API credentials

### ISSUE THREAD

**Issue by igorrendulic** [Amplitude-Developer-Docs/amplitude-dev-center#215]
### What can we improve?

Link to instructions on how to create API credentials for e.g. Privacy API. It would be beneficial to add documentation on HTTP API credentials. 

### Which page needs an update?

https://www.docs.developers.amplitude.com/analytics/

**Comment by caseyamp** [comment]
Added a new article and linked to it from the Auth section of each API ref. Thanks for reporting @igorrendulic
