### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Long889912** [Amplitude-Developer-Docs/amplitude-dev-center#250]
### Contact Details

long.cheng@planetart.cn

### What happened?

I updated the parameters of the event, Optional • Any -> Required • String

$ ampli pull

⚠ WARNING There are 3 pending changes in the tracking plan that are not included in the generated library.

iOS: "Ampli.m"  nothing changes

### Relevant log output

```shell
ampli pull
Source: ios
Runtime: iOS/Obj-C
Branch: main
✔ Pulling version 13 (latest)

⚠ WARNING There are 3 pending changes in the tracking plan that are not included in the generated library.
✔ All events are up to date.
✔ Tracking library generated successfully.
  ↳ Path: ./Ampli
```

**Comment by caseyamp** [comment]
Hello @Long889912 -- this is the repo for the developer docs, we have a small team of writers and can't help troubleshoot product problems. Please post your question in the [Amplitude Community](https://community.amplitude.com/). If you have a paid Amplitude plan, you can also [contact support](https://help.amplitude.com/hc/en-us/articles/360041266311-Amplitude-Support-Offerings-and-Policy#h_afcf9221-2930-4ae2-a5b8-cd16c403db72).

**Comment by caseyamp** [comment]
Housekeeping: closing. Nothing to be done docs-wise.
