### ISSUE TITLE
[Improvement]: Invalid JSON in response example

### ISSUE THREAD

**Issue by philippb** [Amplitude-Developer-Docs/amplitude-dev-center#319]
### What can we improve?

The JSON example in [Event Format](https://www.docs.developers.amplitude.com/analytics/apis/dashboard-rest-api/#event-format), is not valid JSON.
This makes the response confusing.
Validation tool: https://jsonformatter.curiousconcept.com/#

<img width="985" alt="image" src="https://user-images.githubusercontent.com/374326/195216930-603affa8-e711-49db-8f7b-f881b42dbe30.png">

### Which page needs an update?

https://www.docs.developers.amplitude.com/analytics/apis/dashboard-rest-api/#event-format

**Comment by caseyamp** [comment]
Thanks for reporting @philippb -- it should be fixed on the site any minute now.
