### ISSUE TITLE
[Feedback]: 

### ISSUE THREAD

**Issue by mihai-rdu** [Amplitude-Developer-Docs/amplitude-dev-center#646]
### What feedback do you want to give us?

Could you please include an example of how to set arrays as property values? Thanks!

### Which page needs an update?

https://www.docs.developers.amplitude.com/data/sdks/android-kotlin/

**Comment by Mercy811** [comment]
@mihai-rdu Which property do you refer to specifically? 

one example to set an array as group property https://www.docs.developers.amplitude.com/data/sdks/android-kotlin/#user-groups. 

```
amplitude.setGroup("sport", arrayOf("tennis", "soccer")) // list values
```
