### ISSUE TITLE
[Improvement]: Highlight user ID length restrictions

### ISSUE THREAD

**Issue by jvanderwee** [Amplitude-Developer-Docs/amplitude-dev-center#671]
### What can we improve?

Could you please highlight in bold underlined italics that the user ID needs to be 5 characters or longer? 

### Which page needs an update?

https://www.docs.developers.amplitude.com/data/sdks/android-kotlin/#custom-user-id
https://www.docs.developers.amplitude.com/data/sdks/ios-swift/#set-custom-user-id

**Comment by Mercy811** [comment]
Thanks for your feedback @jvanderwee. [HTTP V2 doc](https://www.docs.developers.amplitude.com/analytics/apis/http-v2-api/?h=http+api#device-ids-and-user-ids-minimum-length) has a better explanation of the requirement of device IDs and user IDs. All our SDKs use that endpoint by default but still it definitely better to have that highlighted in each SDK doc.
