### ISSUE TITLE
[Bug]: Event missing from event list enpoint but it's inside segmentation data

### ISSUE THREAD

**Issue by jaroslaw-weber** [Amplitude-Developer-Docs/amplitude-dev-center#697]
### What happened?

I have an issue with Amplitude API.
Some events have segmentation data but are not in the event list. Why does this happen?

Missing event Id: 56773164
apiKey: '9dc6548098c0cf6fa855fae83a00f9a1'

event list query (axios):

```
{
  url: "events/list",
}
```

The event with this ID is not in the result.

segmentation query (axios):
```
{
  url: "events/segmentation",
  params: {
    e: {
      event_type: "_all",
      group_by: [
        {
          type: "user",
          value: "event_type",
        },
      ],
    },
    start: "20230320T00",
    end: "20230320T00",
    m: "uniques",
    limit: 1000,
  },
}
```

Event id is under seriesLabels in the response.

What may be the issue? 

### What browsers are you seeing the problem on?

Other

**Comment by bgiori** [comment]
Closing since this is a general question rather than a developer docs issue. Please reach out to our community or support with this question. Thanks!
