### ISSUE TITLE
[Improvement]: Typo in docs

### ISSUE THREAD

**Issue by jibow** [Amplitude-Developer-Docs/amplitude-dev-center#846]
### What can we improve?

```
 ampitude.init(API_KEY, undefined, {
+   defaultTracking: {
+     attribution: {
+       excludeReferrers: [location.hostname]
+     },
+   },
  });
```

it should be` amplitude.init` not `ampitude.init`

### Which page needs an update?

https://www.docs.developers.amplitude.com/data/sdks/browser-2/migration/#default-events-tracking

**Comment by kevinpagtakhan** [comment]
Fixed by https://github.com/Amplitude-Developer-Docs/amplitude-dev-center/pull/856
